from karppipeline.modules import karp, karps, sbxrepo
from karppipeline.models import PipelineConfig


def install(config: PipelineConfig, subcommand: str = "all") -> None:
    """
    install does not use the source files, only files already generated by run

    TODO installers always depend on runners and possibly that other installers have run,
    needs to be implemented, but for now assumes that the needed steps are done.
    """
    install_all = False
    if subcommand == "all":
        install_all = True
    cmd_found = False

    if (install_all and "karps" in config.install) or subcommand == "karps":
        karps.install(config)
        cmd_found = True
    if (install_all and "sbxrepo" in config.install) or subcommand == "sbxrepo":
        sbxrepo.install(config)
        cmd_found = True
    if (install_all and "karp" in config.install) or subcommand == "karp":
        karp.install(config)
        cmd_found = True

    if not install_all and not cmd_found:
        raise RuntimeError("command not found")
