from karpspipeline import karp, karps, sbxrepo
from karpspipeline.models import PipelineConfig


def install(config: PipelineConfig, subcommand: str = "all") -> None:
    """
    TODO here we assume that the run is done
    install does not use the source files, only files already generated by run
    """
    install_all = False
    if subcommand == "all":
        install_all = True
    cmd_found = False

    if (install_all and "karps" in config.install) or subcommand == "karps":
        karps.install(config)
        cmd_found = True
    if (install_all and "sbxrepo" in config.install) or subcommand == "sbxrepo":
        sbxrepo.install(config)
        cmd_found = True
    if (install_all and "karp" in config.install) or subcommand == "karp":
        karp.install(config)
        cmd_found = True

    if not install_all and not cmd_found:
        raise RuntimeError("command not found")
